// ctrl shift p
// paste json as code
// pokelistresponse
// enter

// Generated by https://quicktype.io

export interface PokeListResponse {
  count: number;
  next?: string;
  previous?: string;
  results: SmallPokemon[];
}

export interface SmallPokemon {
  name: string;
  url: string;
  id: number;
  img: string;
}
